# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Reuben B"
description: > # this means to ignore newlines until "email:"
   A portfolio to demonstrate some of my work.

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/background_image.jpeg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpeg"

name: 'Reuben B'
author: 'Reuben B'
author_image: "/assets/images/background_image.jpeg"

paginate:	5

url: "https://reubs01.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://twitter.com/dirkfabisch
    desc: Connect with me on linkedin
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
