title: "My Projects"
author: "Reuben B"
description: "I post sporadically — basically whenever the mood hits me."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

#external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/reubenbaulch/"}
#  - {title: Github, icon: github, url: "https://github.com/reubs01"}

external:
  - { title: LinkedIn, icon: "fa-brands fa-linkedin", url: "https://www.linkedin.com/in/reubenbaulch/" }
  - { title: Github, icon: "fa-brands fa-github", url: "https://github.com/reubs01" }


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
